spring:
  application:
    name: 04ribbon-customer
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# 使用自定义负载均衡策略  服务名.ribbon.n
#04ribbon-producer:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.steve.compent.MyRule

