spring:
  application:
    name: 03eureka-producer
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      #开启了权限认证的eureka时，使用的URL
#      defaultZone: http://stevetao:123456@localhost:8761/eureka/

