spring:
  application:
    name: 01steve-consumer
eureka:
  client:
    serviceUrl:
    # 需要注册的eureka地址
     defaultZone: http://localhost:8080/eureka/
    enabled: true  # 设置为false即可禁用
    healthcheck:
      enabled: true
#  instance:
#      preferIpAddress: true
#      instance-id: ${sping.application.name}:${server.port}
#      hostname: consumer
server:
  port: 8082
